# Generated by Django 2.2.12 on 2022-10-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='town_city',
        ),
        migrations.AddField(
            model_name='userbase',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
